// Generated by CoffeeScript 1.6.3
/* 
Prefix all variables with `____` to avoid polluting the jade namespace.
*/

var ____jade, ____james,
  _this = this;

____jade = require("jade");

____james = require("james");

module.exports = function(____options) {
  var ____variables;
  if (____options.variables != null) {
    ____variables = ____options.variables;
  }
  ____options.variables = void 0;
  return ____james.createStream(function(____file, ____callback) {
    return ____callback(____jade.compile(____file, ____options)(____variables));
  });
};
